attack(Supply_Chain, Configuration_Environment_Manipulation).
parentOf(Configuration_Environment_Manipulation, Manipulating_Writeable_Configuration_Files).
parentOf(Configuration_Environment_Manipulation, Manipulating_Writeable_Configuration_Files).
parentOf(Configuration_Environment_Manipulation, Manipulating_Writeable_Configuration_Files).
parentOf(Configuration_Environment_Manipulation, Manipulating_Writeable_Configuration_Files).
parentOf(Configuration_Environment_Manipulation, Manipulating_Writeable_Configuration_Files).


parentOf(Configuration_Environment_Manipulation, Manipulating_Writeable_Configuration_Files).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Acceptance_of_Extraneous_Untrusted_Data_With_Trusted_Data).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Improper_Control_of_Resource_Identifiers).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Improper_Neutralization_of_Special_Elements_used_in_a_Command).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Origin_Validation_Error).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Missing_Support_for_Integrity_Check).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Improper_Validation_of_Integrity_Check_Value).
related_weaknesses(Manipulating_Writeable_Configuration_Files,OWASP_Top_Ten_2007_Category_A2_Injection_Flaws).
prerequisites(Manipulating_Writeable_Configuration_Files, Configuration_files_must_be_modifiable_by_the_attacker).
mitigations(Manipulating_Writeable_Configuration_Files, Design, Enforce_principle_of_least_privilege).
mitigations(Manipulating_Writeable_Configuration_Files, Design, Backup_copies_of_all_configuration_files).
mitigations(Manipulating_Writeable_Configuration_Files, Design, Backup_copies_of_all_configuration_files).
mitigations(Manipulating_Writeable_Configuration_Files, Implementation, Integrity_monitoring_for_configuration_files ).
mitigations(Manipulating_Writeable_Configuration_Files, Implementation, Enforce_audit_logging_on_code_and_configuration_promotion_procedures).
mitigations(Manipulating_Writeable_Configuration_Files, Implementation, Load_configuration_from_separate_process_and_memory_space_for_example_a_separate_physical_device_like_a_CD).


