%Configuration_Environment_Manipulation
attack(Supply_Chain,_Configuration_Environment_Manipulation).
parentOf(Configuration_Environment_Manipulation,Manipulating_Writeable_Configuration_Files).
parentOf(Configuration_Environment_Manipulation,Manipulate_Registry_Information).
parentOf(Configuration_Environment_Manipulation,Schema_Poisoning).
parentOf(Configuration_Environment_Manipulation,Data_Injected_During_Configuration).
parentOf(Configuration_Environment_Manipulation,Disable_Security_Software).
prerequisites(Configuration_Environment_Manipulation,The_target_application_must_consult_external_files_or_configuration_controls_to_control_its_execution).
related_weaknesses(Configuration_Environment_Manipulation,External_Control_of_System_or_Configuration_Setting).
related_weaknesses(Configuration_Environment_Manipulation,Improper_Hardware_Lock_Protection_for_Security_Sensitive_Controls).
related_weaknesses(Configuration_Environment_Manipulation,Hardware_Internal_or_Debug_Modes_Allow_Override_of_Locks).

%Manipulating_Writeable_Configuration_Files
attack(Configuration_Environment_Manipulation,Manipulating_Writeable_Configuration_Files).
prerequisites(Manipulating_Writeable_Configuration_Files,Configuration_files_must_be_modifiable_by_the_attacker).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Acceptance_of_Extraneous_Untrusted_Data_With_Trusted_Data).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Improper_Control_of_Resource_Identifiers).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Improper_Neutralization_of_Special_Elements_used_in_a_Command).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Origin_Validation_Error).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Missing_Support_for_Integrity_Check).
related_weaknesses(Manipulating_Writeable_Configuration_Files,Improper_Validation_of_Integrity_Check_Value).
related_weaknesses(Manipulating_Writeable_Configuration_Files,OWASP_Top_Ten_2007_Category_A2_Injection_Flaws).
prerequisites(Manipulating_Writeable_Configuration_Files,_Configuration_files_must_be_modifiable_by_the_attacker).
mitigations(Manipulating_Writeable_Configuration_Files,Design,Enforce_principle_of_least_privilege).
mitigations(Manipulating_Writeable_Configuration_Files,Design,Backup_copies_of_all_configuration_files).
mitigations(Manipulating_Writeable_Configuration_Files,Implementation,Integrity_monitoring_for_configuration_files_).
mitigations(Manipulating_Writeable_Configuration_Files,Implementation,Enforce_audit_logging_on_code_and_configuration_promotion_procedures).
mitigations(Manipulating_Writeable_Configuration_Files,Implementation,Load_configuration_from_separate_process_and_memory_space_for_example_a_separate_physical_device_like_a_CD).

%Manipulate_Registry_Information
attack(Configuration_Environment_Manipulation,Manipulate_Registry_Information).
parentOf(Manipulate_Registry_Information,Poison_Web_Service_Registry).
parentOf(Manipulate_Registry_Information,Modification_of_Registry_Run_Keys).
parentOf(Manipulate_Registry_Information,Modification_of_Windows_Service_Configuration).
prerequisites(Manipulate_Registry_Information,The_targeted_application_must_rely_on_values_stored_in_a_registry).
prerequisites(Manipulate_Registry_Information,The_adversary_must_have_a_means_of_elevating_permissions_in_order_to_access_and_modify_registry_content_through_either_administrator_privileges_or_a_remote_access_tool_capable_of_editing_a_registry_through_an_API).
related_weaknesses(Manipulate_Registry_Information,External_Control_of_System_or_Configuration_Setting).
mitigations(Manipulate_Registry_Information,Ensure_proper_permissions_are_set_for_Registry_hives_to_prevent_users_from_modifying_keys).
mitigations(Manipulate_Registry_Information,Employ_a_robust_and_layered_defensive_posture_in_order_to_prevent_unauthorized_users_on_your_system).
mitigations(Manipulate_Registry_Information,Employ_robust_identification_and_audit_blocking_using_an_allowlist_of_applications_on_your_system).


%Poison_Web_Service_Registry
attack(Manipulate_Registry_Information,Poison_Web_Service_Registry).
prerequisites(Poison_Web_Service_Registry,The_attacker_must_be_able_to_write_to_resources_or_redirect_access_to_the_service_registry).
related_weaknesses(Poison_Web_Service_Registry,Improper_Authorization).
related_weaknesses(Poison_Web_Service_Registry,Improper_Neutralization_of_Special_Elements_in_Output_Used_by_a_Downstream_Component).
related_weaknesses(Poison_Web_Service_Registry,Protection_Mechanism_Failure).
mitigations(Poison_Web_Service_Registry,Design,Enforce_principle_of_least_privilege).
mitigations(Poison_Web_Service_Registry,Design,Harden_registry_server_and_file_access_permissions).
mitigations(Poison_Web_Service_Registry,Implementation,Implement_communications_to_and_from_the_registry_using_secure_protocols).

%Modification_of_Registry_Run_Keys
attack(Manipulate_Registry_Information,Modification_of_Registry_Run_Keys).
prerequisites(Modification_of_Registry_Run_Keys,The_adversary_must_have_gained_access_to_the_target_system_via_physical_or_logical_means_in_order_to_carry_out_this_attack).
related_weaknesses(Modification_of_Registry_Run_Keys,External_Control_of_System_or_Configuration_Setting).
mitigations(Modification_of_Registry_Run_Keys,Identify_programs_that_may_be_used_to_acquire_process_information_and_block_them_by_using_a_software_restriction_policy_or_tools_that_restrict_program_execution_by_using_a_process_allowlist).

%Modification_of_Windows_Service_Configuration
attack(Manipulate_Registry_Information,Modification_of_Windows_Service_Configuration).
prerequisites(Modification_of_Windows_Service_Configuration,The_adversary_must_have_the_capability_to_write_to_the_Windows_Registry_on_the_targeted_system).
related_weaknesses(Modification_of_Windows_Service_Configuration,Improper_Access_Control).
mitigations(Modification_of_Windows_Service_Configuration,Ensure_proper_permissions_are_set_for_Registry_hives_to_prevent_users_from_modifying_keys_for_system_components_that_may_lead_to_privilege_escalation).


/*Schema Poisoning*/
attack(Configuration_Environment_Manipulation,Schema_Poisoning).
prerequisites(Schema_Poisoning,Some_level_of_access_to_modify_the_target_schema).
prerequisites(Schema_Poisoning,The_schema_used_by_the_target_application_must_be_improperly_secured_against_unauthorized_modification_and_manipulation).
mitigations(Schema_Poisoning,Design,Protect_the_schema_against_unauthorized_modification).
mitigations(Schema_Poisoning,Implementation,For_applications_that_use_a_known_schema_use_a_local_copy_or_a_known_good_repository_instead_of_the_schema_reference_supplied_in_the_schema_document).
mitigations(Schema_Poisoning,Implementation,For_applications_that_leverage_remote_schemas_use_the_HTTPS_protocol_to_prevent_modification_of_traffic_in_transit_and_to_avoid_unauthorized_modification).
/*Consequences????*/

/*Data Injected During Configuration*/
attack(Configuration_Environment_Manipulation,Data_Injected_During_Configuration).
prerequisites(Data_Injected_During_Configuration,The_attacker_must_have_previously_compromised_the_victims_systems_or_have_physical_access_to_the_victims_systems).
prerequisites(Data_Injected_During_Configuration,Advanced_knowledge_of_software_and_hardware_capabilities_of_a_manufacturers_product).
mitigations(Data_Injected_During_Configuration,Ensure_that_proper_access_control_is_implemented_on_all_systems_to_prevent_unauthorized_access_to_system_files_and_processe).

/*Disable Security Software*/
attack(Configuration_Environment_Manipulation,Disable_Security_Software).
prerequisites(Disable_Security_Software,The_adversary_must_have_the_capability_to_interact_with_the_configuration_of_the_targeted_system).
mitigations(Disable_Security_Software,Ensure_proper_permissions_are_in_place_to_prevent_adversaries_from_altering_the_execution_status_of_security_tools).


/*Manipulation During Distribution*/
parentOf(Manipulation_During_Distribution,Malicious_Hardware_Componen_Replacement).
parentOf(Manipulation_During_Distribution,Malicious_Software_Implanted).
parentOf(Manipulation_During_Distribution,Rogue_Integration_Procedures).

attack(Supply_Chain, Manipulation_During_Distribution).
related_weaknesses(Manipulation_During_Distribution,Product_Released_in_Non_Release_Configuration).

/*Malicious Hardware Component Replacement*/
attack(Manipulation_During_Distribution,Malicious_Hardware_Component_Replacement).
prerequisites(Malicious_Hardware_Component_Replacement,Physical_access_to_the_system_after_it_has_left_the_manufacturer_but_before_it_is_deployed_at_the_victim_location).

/*Malicious Software Implanted*/
attack(Manipulation_During_Distribution,Maliciou_Software_Implanted).
prerequisites(Maliciou_Software_Implanted,Physical_access_to_the_system_after_it_has_left_the_manufacturer_but_before_it_is_deployed_at_the_victim_location).

/*Modification_During_Manufacture*/
attack(Supply_Chain,Modification_During_Manufacture).
parentOf(Modification_During_Manufacture, Development_Alteration).
parentOf(Modification_During_Manufacture, Design_Alteration).

/*Development_Alteration*/
parentOf(Development_Alteration, Malicious_Logic_Inserted_Into_Product_Software_by_Authorized_Developer).
parentOf(Development_Alteration, Malicious_Logic_Insertion_into_Product_Software_via_Configuration_Management_Manipulation).
parentOf(Development_Alteration, Malicious_Logic_Insertion_into_Product_Software_via_Inclusion_of_3rd_Party_Component_Dependency).
parentOf(Development_Alteration, Infiltration_of_Software_Development_Environment).
parentOf(Development_Alteration, Hardware_Component_Substitution_During_Baselining).
parentOf(Development_Alteration, Counterfeit_Hardware_Component_Inserted_During_Product_Assembly).
parentOf(Development_Alteration, Altered_Installed_BIOS).
parentOf(Development_Alteration, Infiltration_of_Hardware_Development_Environment).
parentOf(Development_Alteration, Open_Source_Libraries_Altered).
parentOf(Development_Alteration, ASIC_With_Malicious_Functionality).

prerequisites(Development_Alteration, Access_to_the_system_during_the_development_phase_to_alter_and_or_modify_software_and_hardware_components).
mitigations(Development_Alteration, Assess_Software_and_software_components_during_development_and_prior_to_deployment_to_ensure_that_they_function_as_intended_and_without_any_malicious_functionality).

prerequisites(Malicious_Logic_Inserted_Into_Product_Software_by_Authorized_Developer, Access_to_the_software_during_the_development_phase).
mitigations(Malicious_Logic_Inserted_Into_Product_Software_by_Authorized_Developer, Assess_Software_and_software_components_during_development_and_prior_to_deployment_to_ensure_that_they_function_as_intended_and_without_any_malicious_functionality).

prerequisites(Malicious_Logic_Insertion_into_Product_Software_via_Configuration_Management_Manipulation, Access_to_the_configuration_management_system_during_deployment_or_currently_deployed_at_a_victim_location).
mitigations(Malicious_Logic_Insertion_into_Product_Software_via_Configuration_Management_Manipulation, Assess_Software_and_software_components_during_development_and_prior_to_deployment_to_ensure_that_they_function_as_intended_and_without_any_malicious_functionality).
mitigations(Malicious_Logic_Insertion_into_Product_Software_via_Configuration_Management_Manipulation, Leverage_anti-virus_products_to_detect_and_quarantine_software_with_known_virus).

prerequisites(Malicious_Logic_Insertion_into_Product_Software_via_Inclusion_of_3rd_Party_Component_Dependency, Access_to_the_software_during_the_development_phase).
mitigations(Malicious_Logic_Insertion_into_Product_Software_via_Inclusion_of_3rd_Party_Component_Dependency, Assess_Software_and_software_components_during_development_and_prior_to_deployment_to_ensure_that_they_function_as_intended_and_without_any_malicious_functionality).

prerequisites(Infiltration_of_Software_Development_Environment, The_victim_must_use_email_or_removable_media_from_systems_running_the_IDE).
prerequisites(Infiltration_of_Software_Development_Environment, The_victim_must_have_a_system_running_exploitable_applications_and_or_a_vulnerable_configuration).
prerequisites(Infiltration_of_Software_Development_Environment, The_attacker_must_have_working_knowledge_of_the_components_involved_in_IDE_and_infrastructure).

prerequisites(Hardware_Component_Substitution_During_Baselining, The_attacker_need_physical_access_or_be_able_to_supply_malicious_hardware_components_to_the_product_development_facility).

prerequisites(Counterfeit_Hardware_Component_Inserted_During_Product_Assembly, The_attacker_need_physical_access_or_be_able_to_supply_malicious_hardware_components_to_the_product_development_facility).

prerequisites(Altered_Installed_BIOS, Advanced_knowledge_about_the_installed_target_system_design).
prerequisites(Altered_Installed_BIOS, Advanced_knowledge_about_the_download_and_update_installation_processes).
prerequisites(Altered_Installed_BIOS, Access_to_the_download_and_update_systems_used_to_deliver_BIOS_images).


prerequisites(Infiltration_of_Hardware_Development_Environment, The_victim_must_use_email_or_removable_media_from_systems_running_the_IDE).
prerequisites(Infiltration_of_Hardware_Development_Environment, The_victim_must_have_a_system_running_exploitable_applications_and_or_a_vulnerable_configuration).
prerequisites(Infiltration_of_Hardware_Development_Environment, The_attacker_must_have_working_knowledge_of_the_components_involved_in_IDE_and_infrastructure).

prerequisites(Open_Source_Libraries_Altered,Access_to_the_open_source_code_base_being_used_by_the_manufacturer_in_system_being_developed_or_currently_deployed_at_victim_location).

prerequisites(ASIC_With_Malicious_Functionality, Advanced_knowledge_about_ASIC_installed_within_the_target_system).
prerequisites(ASIC_With_Malicious_Functionality, The_attacker_must_have_working_knowledge_of_the_components_involved_in_target_system_as_well_infrastructure_and_development_environment_of_the_manufacturer).

/*Design_Alteration*/
prerequisites(Design_Alteration, Access_to_system_design_documentation_prior_to_the_development_phase).
prerequisites(Design_Alteration, Ability_to_forge_web_communications_to_deliver_modified_design_documentation).
mitigations(Design_Alteration, Assess_design_documentation_during_development_and_prior_to_deployment_to_ensure_that_they_function_as_intended_and_without_any_malicious_functionality).
mitigations(Design_Alteration, Ensure_that_design_documentation_is_saved_in_a_secure_location_and_has_proper_access_controls_set_in_place_to_avoid_unnecessary_modification).
parentOf(Design_Alteration, Documentation_Alteration_to_Circumvent_Dial_down).
parentOf(Design_Alteration, Documentation_Alteration_to_Produce_Under_performing_Systems).
parentOf(Design_Alteration, Documentation_Alteration_to_Cause_Errors_in_System_Design).
parentOf(Design_Alteration, Hardware_Design_Specifications_Are_Altered).

prerequisites(Documentation_Alteration_to_Circumvent_Dial_down, Advanced_knowledge_of_internal_software_and_hardware_components_within_manufacturers_development_environment).
prerequisites(Documentation_Alteration_to_Circumvent_Dial_down, Access_to_the_manufacturers_documentation).

prerequisites(Documentation_Alteration_to_Produce_Under_performing_Systems, Advanced_knowledge_of_software_and_hardware_capabilities_of_a_manufacturers_product).
prerequisites(Documentation_Alteration_to_Produce_Under_performing_Systems, Access_to_the_manufacturers_documentation).

prerequisites(Documentation_Alteration_to_Cause_Errors_in_System_Design, Advanced_knowledge_of_software_capabilities_of_a_manufacturers_product).
prerequisites(Documentation_Alteration_to_Cause_Errors_in_System_Design, Access_to_the_manufacturers_documentation).

prerequisites(Hardware_Design_Specifications_Are_Altered, Advanced_knowledge_of_hardware_capabilities_of_a_manufacturers_product).
prerequisites(Hardware_Design_Specifications_Are_Altered, Access_to_the_manufacturers_documentation).

/*Rogue Integration Procedures*/
attack(Manipulation_During_Distribution,Rogue_Integration_Procedures).
prerequisites(Rogue_Integration_Procedures,Physical_access_to_an_integration_facility_that_prepares_the_system_before_it_is_deployed_at_the_victim_location).

